models/Files.php
<?php

namespace app\models;

/**
 * This is the model class for table "files".
 *
 * @property int $id
 * @property string $name
 * @property string|null $path
 * @property string $created_at
 * @property string $updated_at
 */
class Files extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'files';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'path'], 'string', 'max' => 255],
            [['name'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'path' => 'Изображение',
            'created_at' => 'Дата и время загрузки',
            'updated_at' => 'Updated At',
        ];
    }
}

controllers/FileController.php
<?php

namespace app\controllers;

use app\models\Files;
use app\models\forms\FilesSearch;
use app\models\forms\UploadForm;
use Exception;
use Throwable;
use Yii;
use yii\base\ExitException;
use yii\base\InvalidRouteException;
use yii\db\StaleObjectException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use ZipArchive;

/**
 * FileController implements the CRUD actions for Files model.
 */
class FileController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }


    public function actionIndex()
    {
        $searchModel = new FilesSearch();
        $dataProvider = $searchModel->search($this->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }


    public function actionCreate()
    {
        $model = new UploadForm();

        if ($this->request->isPost) {
            if ($model->load($this->request->post())) {
                $model->files = UploadedFile::getInstances($model, 'files');
                $model->saveImage();
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }


    /**
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    /**
     * @throws Throwable
     * @throws StaleObjectException
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * @throws Exception
     */
    public function actionDownloadFile()
    {
        $file = Yii::$app->request->post('file');

        $filename =  Yii::getAlias('@app') . "/web/$file";

        if (!file_exists(trim($filename)))
            self::fileNotFound();

        $zipName = Yii::getAlias('@app') . '/' . date('Yd_m_Y_H_i_s') . '.zip';
        $zip = new ZipArchive();

        if (!$zip->open($zipName, ZipArchive::CREATE))
            throw new Exception('Failed to create ZIP archive');

        $zip->addFile($filename, basename($filename));
        $zip->close();
        Yii::$app->response->sendFile($zipName);
        unlink($zipName);
    }


    /**
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        if (($model = Files::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * @throws ExitException
     * @throws InvalidRouteException
     */
    private static function fileNotFound(): void
    {
        Yii::$app->session->setFlash('error', 'Изображение не найдено');
        $url = Yii::$app->request->referrer;
        Yii::$app->getResponse()->redirect($url);
        Yii::$app->end();
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use yii\web\Controller;

class SiteController extends Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

}

views/file/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\forms\UploadForm $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="files-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'files[]')->fileInput(['class' => 'form-control', 'multiple' => true]); ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/file/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var app\models\forms\FilesSearch $model */
/** @var yii\widgets\ActiveForm $form */
?>

<div class="files-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'path') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/file/create.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Files $model */

$this->title = 'Create Files';
$this->params['breadcrumbs'][] = ['label' => 'Files', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="files-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/file/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/** @var yii\web\View $this */
/** @var app\models\forms\FilesSearch $searchModel */
/** @var yii\data\ActiveDataProvider $dataProvider */

$this->title = 'Список изображений';
$this->params['breadcrumbs'][] = $this->title;

$css = <<<CSS
.pagination {
    margin-top: 20px;
    justify-content: center;
}
CSS;

$this->registerCss($css);

?>
<div class="files-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить изображение', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            [
                'attribute' => 'path',
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::a(
                        Html::img($model->path, ['width' => '100px']),
                        $model->path,
                        ['target' => '_blank']
                    );
                },
            ],
            [
                'attribute' => 'created_at',
                'value' => function ($data) {
                    $date = new DateTime($data->created_at);
                    return $date->format('d.m.Y H:i:s');
                },
            ],
            [
                'label' => 'Скачать',
                'format' => 'raw',
                'contentOptions' => ['style' => 'width: 120px; justify-content: center; align-items: center;'],
                'value' => function ($data) {
                    return Html::beginForm(Url::to(['file/download-file']), 'post') .
                        Html::hiddenInput('file', $data->path) .
                        Html::submitButton('Скачать изображение', [
                            'class' => 'btn btn-primary',
                            'onclick' => 'event.preventDefault(); this.form.submit();',
                        ]) .
                        Html::endForm();
                },
            ],

        ],
        'pager' => [
            'class' => \yii\widgets\LinkPager::class,
            'options' => [
                'class' => 'pagination',
                'activePageCssClass' => 'page-item active',
                'disabledPageCssClass' => 'disabled page-item',
                'pageCssClass' => 'page-item',
                'linkOptions' => ['class' => 'page-link'],
                'disabledListItemSubTagOptions' => ['tag' => 'a', 'class' => 'page-link disabled'],
            ],
        ],
    ]); ?>


</div>

views/file/update.php
<?php

use yii\helpers\Html;

/** @var yii\web\View $this */
/** @var app\models\Files $model */

$this->title = 'Update Files: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Files', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="files-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/file/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/** @var yii\web\View $this */
/** @var app\models\Files $model */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Files', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="files-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'path',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap5\Breadcrumbs;
use yii\bootstrap5\Html;
use yii\bootstrap5\Nav;
use yii\bootstrap5\NavBar;

AppAsset::register($this);

$this->registerCsrfMetaTags();
$this->registerMetaTag(['charset' => Yii::$app->charset], 'charset');
$this->registerMetaTag(['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no']);
$this->registerMetaTag(['name' => 'description', 'content' => $this->params['meta_description'] ?? '']);
$this->registerMetaTag(['name' => 'keywords', 'content' => $this->params['meta_keywords'] ?? '']);
$this->registerLinkTag(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => Yii::getAlias('@web/favicon.ico')]);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header id="header">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => ['class' => 'navbar-expand-md navbar-dark bg-dark fixed-top']
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Список изображений', 'url' => ['/file/index']],
        ]
    ]);
    NavBar::end();
    ?>
</header>

<main id="main" class="flex-shrink-0" role="main">
    <div class="container">
        <?php if (!empty($this->params['breadcrumbs'])): ?>
            <?= Breadcrumbs::widget(['links' => $this->params['breadcrumbs']]) ?>
        <?php endif ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer id="footer" class="mt-auto py-3 bg-light">
    <div class="container">
        <div class="row text-muted">
            <div class="col-md-6 text-center text-md-start">Хостинг изображений</div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/index.php
<?php

/** @var yii\web\View $this */

$this->title = 'Главная';
?>
<div class="site-index">
    <div class="jumbotron text-center bg-transparent mt-5 mb-5">
        <h1 class="display-4">Хостинг изображений</h1>

        <p class="lead">Здесь можно увидеть список загруженных изображений, скачать и загрузить</p>

        <p><a class="btn btn-lg btn-success" href="/file/">Перейти к списку</a></p>
    </div>
</div>